version: "2"
services:
    web:
        container_name: web
        restart: always
        build: ./tiles-client
        ports:
        - "3000:3000"
        links:
            - mongo
            - api
    api:
        container_name: api
        restart: always
        build: ./tiles-api
        ports:
            - "4001:4001"
        links:
            - mongo
            - api
    mongo:
        container_name: mongo
        image: mongo
        volumes:
        - ./data:/data/db
        ports:
        - "27017:27017"